### ISSUE TITLE
 attempt to call upvalue 'Statsd' (a table value)

### ISSUE THREAD

**Issue by ramamoob** [stvp/lua-statsd-client#9]
Hi,
I am new to lua. I am following the steps provided in README.md. Whenever I try to run my code I am getting the runtime error as mentioned above.

Here is my code snippet.

```
local Statsd = require "statsd"
statsd_obj = Statsd({namespace = "test.stats"})

statsd_obj:increment(message["request"]["uri"])
```
Can you please help?

From the error it seems like I am trying to call Statsd as a function where as it is a table. 
How can I call the Statsd as a function?

**Comment by moteus** [comment]
I can suggest you use different statsd library. Because this library [return function](https://github.com/stvp/lua-statsd-client/blob/master/src/statsd.lua#L126-L151)
Try figureout which one file loaded by `local Statsd = require "statsd"` and checkout source.
I use this library without any issues to collect system info from ~10 servers.

**Comment by ramamoob** [comment]
Thanks for your response. Can you please let me know how you are instantiating the statsd object and calling its methods in your code.

**Comment by moteus** [comment]
I think this is almost complite [example](https://github.com/moteus/lua-pdh/blob/master/examples/system_monitor.lua). I run it as service.

**Comment by ramamoob** [comment]
Thanks for your example. I am still running into the same issue. I followed your guidance as shown in your example. Below is my code snippet.

```
local CONFIG = {

      STATSD = {
        NAMESPACE = "test.stats";
        HOST = "127.0.0.1";
        PORT = "8125";
        SEND_TABLE = false;
     };
  };

local Statsd = assert(require "statsd"
  {
      host= CONFIG.STATSD.HOST,
      port = CONFIG.STATSD.PORT,
      namespace = CONFIG.STATSD.NAMESPACE
  })

  Statsd:increment(message["status"], 1)

```
During runtime I get this error

```
 attempt to call a table value
```

Do you know what I am doing wrong?

**Comment by moteus** [comment]
You use differen library i think

**Comment by ramamoob** [comment]
This is the library I am running.

```
statsd 3.0.2-1 - Statsd client.

Statsd client for Lua 5.1+. Uses the luasocket library for UDP.

License:        MIT/X11
Homepage:       https://github.com/stvp/lua-statsd-client
Installed in:   /usr/local

Modules:
        statsd (/usr/local/share/lua/5.1/statsd.lua)

Depends on:
        luasocket
```

**Comment by moteus** [comment]
1. try find out what table contain. e.g. print all key/values
`for k,v in pairs(statsd) do print(k,v) end`
2. try find all statusd.lua files and findout which one loaded when you call require.
(it also can be .so/.dll)
Contains of statsd can help in this.
search in directories which you have in package.path/cpath

**Comment by ramamoob** [comment]
I checked what is in the table. I am printing the key and the type of the value. The output here is from just require 'statsd'. 

```
2015/10/23 19:47:20 [error] 20884#0: [lua] log.lua:38: Type of statsd: table, context: ngx.timer, client: X.X.X.X, server: 0.0.0.0:8000
2015/10/23 19:47:20 [error] 20884#0: [lua] log.lua:39: incr - function, context: ngx.timer, client: X.X.X.X, server: 0.0.0.0:8000
2015/10/23 19:47:20 [error] 20884#0: [lua] log.lua:39: flush - function, context: ngx.timer, client: X.X.X.X, server: 0.0.0.0:8000
2015/10/23 19:47:20 [error] 20884#0: [lua] log.lua:39: buffer - table, context: ngx.timer, client: X.X.X.X, server: 0.0.0.0:8000
2015/10/23 19:47:20 [error] 20884#0: [lua] log.lua:39: count - function, context: ngx.timer, client: X.X.X.X, server: 0.0.0.0:8000
2015/10/23 19:47:20 [error] 20884#0: [lua] log.lua:39: register - function, context: ngx.timer, client: X.X.X.X, server: 0.0.0.0:8000
2015/10/23 19:47:20 [error] 20884#0: [lua] log.lua:39: time - function, context: ngx.timer, client: X.X.X.X, server: 0.0.0.0:8000
```

I also see that the statsd.lua is loaded from the location 
```
/usr/local/share/lua/5.1/statsd.lua
```

It is the exact same code as the one in this repo.

**Comment by ramamoob** [comment]
I am able to set the table values like this

```
local statsd = require "statsd"
  statsd["host"] = CONFIG.STATSD.HOST
  statsd["port"] = CONFIG.STATSD.PORT
  statsd["namespace"] = CONFIG.STATSD.NAMESPACE
```
When I try to call the function
```
statsd.increment(message["status"], 1)
```
I get the error method
```
attempt to call field 'increment' (a nil value)
```

**Comment by ramamoob** [comment]
I think I made some progress. Right now I can confirm that it is loading the correct statsd.lua. But is failing within that code on line #22.

```
2015/10/23 20:45:42 [error] 4187#0: lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/statsd.lua:22: attempt to index local 'stat' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/share/lua/5.1/statsd.lua: in function 'make_statsd_message'
        /usr/local/share/lua/5.1/statsd.lua:67: in function 'increment'
```

Which is 

https://github.com/stvp/lua-statsd-client/blob/master/src/statsd.lua#L22

**Comment by ramamoob** [comment]
you can close this case. Thanks for all your help.
